version: '3'

services:
  postgres:
    image: postgres:12.9-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - docker/postgres/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - base-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 15432:80
    user: root
    env_file:
      - docker/pgadmin/pgadmin.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - base-network
    depends_on:
      - postgres

  app:
    container_name: app
    image: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - docker/postgres/postgres.env
      - .env
    networks:
      - base-network
    depends_on:
      - postgres

volumes:
  postgres-data: {}
  pgadmin-data: {}

networks:
  base-network:
    driver: bridge
