version: '3'

services:
  postgres:
    image: postgres:12.9-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - docker/postgres/postgres.env
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      base-network:
        ipv4_address: 172.16.0.2

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 15432:80
    user: root
    env_file:
      - docker/pgadmin/pgadmin.env
    volumes:
      - ./docker/pgadmin/data:/var/lib/pgadmin
    networks:
      base-network:
        ipv4_address: 172.16.0.3
    depends_on:
      - postgres

  app:
    container_name: app
    image: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - docker/postgres/postgres.env
      - .env
    networks:
      base-network:
        ipv4_address: 172.16.0.4
    depends_on:
      - postgres
      - pgadmin

networks:
  base-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
